-- 统一服务发起表
-- 整合外出请求和服务执行，统一服务发起流程
-- 支持：普通服务执行、外出服务、跨部门服务

CREATE TABLE IF NOT EXISTS `project_service_launch` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `contract_id` bigint DEFAULT NULL COMMENT '关联合同ID',
    `project_id` bigint DEFAULT NULL COMMENT '关联项目ID',
    `service_item_id` bigint NOT NULL COMMENT '关联服务项ID',
    `service_item_dept_id` bigint DEFAULT NULL COMMENT '服务项归属部门ID',
    `execute_dept_id` bigint NOT NULL COMMENT '执行部门ID',
    `request_user_id` bigint DEFAULT NULL COMMENT '发起人ID',
    `request_dept_id` bigint DEFAULT NULL COMMENT '发起人部门ID',
    `is_outside` tinyint(1) DEFAULT 0 COMMENT '是否外出：0否 1是',
    `is_cross_dept` tinyint(1) DEFAULT 0 COMMENT '是否跨部门：0否 1是（服务项归属部门 != 执行部门）',
    `destination` varchar(500) DEFAULT NULL COMMENT '外出地点（仅外出时有值）',
    `reason` varchar(1000) DEFAULT NULL COMMENT '外出事由（仅外出时有值）',
    `plan_start_time` datetime DEFAULT NULL COMMENT '计划开始时间',
    `plan_end_time` datetime DEFAULT NULL COMMENT '计划结束时间',
    `executor_ids` varchar(500) DEFAULT NULL COMMENT '执行人ID列表（JSON数组，审批时选择）',
    `executor_names` varchar(500) DEFAULT NULL COMMENT '执行人姓名列表（逗号分隔）',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0待审批 1已通过 2已拒绝 3已取消',
    `process_instance_id` varchar(64) DEFAULT NULL COMMENT '工作流流程实例ID',
    `round_id` bigint DEFAULT NULL COMMENT '创建的轮次ID（审批通过后）',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `authorization_urls` text DEFAULT NULL COMMENT '授权书附件URL（JSON数组，渗透测试）',
    `test_scope_urls` text DEFAULT NULL COMMENT '测试范围附件URL（JSON数组，渗透测试）',
    `credentials_urls` text DEFAULT NULL COMMENT '账号密码附件URL（JSON数组，渗透测试）',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_contract_id` (`contract_id`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_service_item_id` (`service_item_id`),
    KEY `idx_request_user_id` (`request_user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_is_cross_dept` (`is_cross_dept`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一服务发起表';
