<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.shuhe</groupId>
        <artifactId>shuhe</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>shuhe-module-finance</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>
        finance 模块，财务管理模块。
        主要实现：项目预算分配、服务项收入分配、合同资金管理等功能。
        后续将整合员工成本、经营分析等财务相关功能。
    </description>

    <dependencies>
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-module-system</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-module-infra</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- Web 相关 -->
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-spring-boot-starter-mybatis</artifactId>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-spring-boot-starter-excel</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>cn.shuhe</groupId>
            <artifactId>shuhe-spring-boot-starter-test</artifactId>
        </dependency>
    </dependencies>
</project>
